[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mtobjects"
version = "0.1.0"
description = "Max-tree based object detection and parameter extraction"
authors = ["Caroline Haigh <caroline@example.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/PabloMSanAla/mtobjects"
repository = "https://github.com/PabloMSanAla/mtobjects"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "mtolib"}]
include = [
    "mto.py",
    "mtolib/src/*.c",
    "mtolib/src/*.h",
    "mtolib/lib/*.so",
    "Makefile"
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "*"
astropy = "*"
Pillow = "*"
scikit-image = "*"
matplotlib = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

# Custom scripts that run before/after build
[tool.poetry.scripts]
# We can add compilation scripts here if needed
